# Generated by Django 5.1.7 on 2025-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='words',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
